export enum RoverMode {
	ROVER_MODE_MANUAL = 0, // MANUAL
	ROVER_MODE_ACRO = 1, // ACRO
	ROVER_MODE_STEERING = 3, // STEERING
	ROVER_MODE_HOLD = 4, // HOLD
	ROVER_MODE_LOITER = 5, // LOITER
	ROVER_MODE_FOLLOW = 6, // FOLLOW
	ROVER_MODE_SIMPLE = 7, // SIMPLE
	ROVER_MODE_DOCK = 8, // DOCK
	ROVER_MODE_CIRCLE = 9, // CIRCLE
	ROVER_MODE_AUTO = 10, // AUTO
	ROVER_MODE_RTL = 11, // RTL
	ROVER_MODE_SMART_RTL = 12, // SMART RTL
	ROVER_MODE_GUIDED = 15, // GUIDED
	ROVER_MODE_INITIALIZING = 16, // INITIALISING
	ROVER_MODE_ENUM_END = 17, // 
}