export enum SubMode {
	SUB_MODE_STABILIZE = 0, // STABILIZE
	SUB_MODE_ACRO = 1, // ACRO
	SUB_MODE_ALT_HOLD = 2, // ALT HOLD
	SUB_MODE_AUTO = 3, // AUTO
	SUB_MODE_GUIDED = 4, // GUIDED
	SUB_MODE_CIRCLE = 7, // CIRCLE
	SUB_MODE_SURFACE = 9, // SURFACE
	SUB_MODE_POSHOLD = 16, // POSHOLD
	SUB_MODE_MANUAL = 19, // MANUAL
	SUB_MODE_MOTORDETECT = 20, // MOTORDETECT
	SUB_MODE_SURFTRAK = 21, // SURFTRAK
	SUB_MODE_ENUM_END = 22, // 
}