export enum TrackerMode {
	TRACKER_MODE_MANUAL = 0, // MANUAL
	TRACKER_MODE_STOP = 1, // STOP
	TRACKER_MODE_SCAN = 2, // SCAN
	TRACKER_MODE_SERVO_TEST = 3, // SERVO TEST
	TRACKER_MODE_GUIDED = 4, // GUIDED
	TRACKER_MODE_AUTO = 10, // AUTO
	TRACKER_MODE_INITIALIZING = 16, // INITIALISING
	TRACKER_MODE_ENUM_END = 17, // 
}